#    http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/de/
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/de/instance_types_en_uris_de.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/de/mappingbased_properties_en_uris_de.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/de/specific_mappingbased_properties_en_uris_de.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/de/labels_en_uris_de.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/de/short_abstracts_en_uris_de.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/de/images_en_uris_de.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/de/infobox_property_definitions_en_uris_de.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/de/article_categories_en_uris_de.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/de/infobox_properties_en_uris_de.nt.bz2
bunzip2 instance_types_en_uris_de.nt.bz2
bunzip2 mappingbased_properties_en_uris_de.nt.bz2
bunzip2 specific_mappingbased_properties_en_uris_de.nt.bz2
bunzip2 labels_en_uris_de.nt.bz2
bunzip2 short_abstracts_en_uris_de.nt.bz2
bunzip2 images_en_uris_de.nt.bz2
bunzip2 infobox_property_definitions_en_uris_de.nt.bz2
bunzip2 article_categories_en_uris_de.nt.bz2
bunzip2 infobox_properties_en_uris_de.nt.bz2
