cp "$1" "$1.bak"
# WAAAH To be clear: On OS X - as of Mountain Lion (10.8.2) - sed does NOT support case-insensitive matching - hard to believe, but true. The # accepted answer gained that status because of the Perl-based solution mentioned in the comments.
#To make that Perl solution work with foreign characters as well, via UTF-8, use something like:
# perl -C 'use utf8;' -pe 's/öœ/oo/' <<< "FÖŒ" # -> "Foo"
# 1085D
# http://www.fileformat.info/info/unicode/char/2022/index.htm
sed 's/%C3%A4/ä/g' "$1" |
sed 's/Ä%/%C4%/g' | # UNDO MESSUP
sed 's/%C3%B6/ö/g' |
sed 's/%C3%BC/ü/g' |
sed 's/%C3%9F/ß/g' |
sed 's/%C3%84/Ä/g' |
sed 's/%C3%96/Ö/g' |
sed 's/%C3%9C/Ü/g' |
sed 's/%C3%A9/é/g' |
sed 's/%C3%B2/ò/g' |
sed 's/%C3%80/À/g' |
sed 's/%C3%81/Á/g' |
sed 's/%C3%82/Â/g' |
sed 's/%C3%83/Ã/g' |
sed 's/%C3%84/Ä/g' |
sed 's/%C3%85/Å/g' |
sed 's/%C3%86/Æ/g' |
sed 's/%C3%87/Ç/g' |
sed 's/%C3%88/È/g' |
sed 's/%C3%89/É/g' |
sed 's/%C3%8A/Ê/g' |
sed 's/%C3%8B/Ë/g' |
sed 's/%C3%8C/Ì/g' |
sed 's/%C3%8D/Í/g' |
sed 's/%C3%8E/Î/g' |
sed 's/%C3%8F/Ï/g' |
sed 's/%C3%90/Ð/g' |
sed 's/%C3%91/Ñ/g' |
sed 's/%C3%92/Ò/g' |
sed 's/%C3%93/Ó/g' |
sed 's/%C3%94/Ô/g' |
sed 's/%C3%95/Õ/g' |
sed 's/%C3%96/Ö/g' |
sed 's/%C3%97/×/g' |
sed 's/%C3%98/Ø/g' |
sed 's/%C3%99/Ù/g' |
sed 's/%C3%9A/Ú/g' |
sed 's/%C3%9B/Û/g' |
sed 's/%C3%9C/Ü/g' |
sed 's/%C3%9D/Ý/g' |
sed 's/%C3%9E/Þ/g' |
sed 's/%C3%9F/ß/g' |
sed 's/%C3%A0/à/g' |
sed 's/%C3%A1/á/g' |
sed 's/%C3%A2/â/g' |
sed 's/%C3%A3/ã/g' |
sed 's/%C3%A4/ä/g' |
sed 's/%C3%A5/å/g' |
sed 's/%C3%A6/æ/g' |
sed 's/%C3%A7/ç/g' |
sed 's/%C3%A8/è/g' |
sed 's/%C3%A9/é/g' |
sed 's/%C3%AA/ê/g' |
sed 's/%C3%AB/ë/g' |
sed 's/%C3%AC/ì/g' |
sed 's/%C3%AD/í/g' |
sed 's/%C3%AE/î/g' |
sed 's/%C3%AF/ï/g' |
sed 's/%C3%B0/ð/g' |
sed 's/%C3%B1/ñ/g' |
sed 's/%C3%B2/ò/g' |
sed 's/%C3%B3/ó/g' |
sed 's/%C3%B4/ô/g' |
sed 's/%C3%B5/õ/g' |
sed 's/%C3%B6/ö/g' |
sed 's/%C3%B7/÷/g' |
sed 's/%C3%B8/ø/g' |
sed 's/%C3%B9/ù/g' |
sed 's/%C3%BA/ú/g' |
sed 's/%C3%BB/û/g' |
sed 's/%C3%BC/ü/g' |
sed 's/%C3%BD/ý/g' |
sed 's/%C3%BE/þ/g' |
sed 's/%C3%BF/ÿ/g' |
sed 's/%E4/ä/g' |
sed 's/%F6/ö/g' |
sed 's/%FC/ü/g' |
sed 's/%DF/ß/g' |
sed 's/%C4/Ä/g' |
sed 's/%D6/Ö/g' |
sed 's/%DC/Ü/g' |
sed 's/\\u00C0/À/g' |
sed 's/\\u00C1/Á/g' |
sed 's/\\u00C2/Â/g' |
sed 's/\\u00C3/Ã/g' |
sed 's/\\u00C4/Ä/g' |
sed 's/\\u00C5/Å/g' |
sed 's/\\u00C6/Æ/g' |
sed 's/\\u00C7/Ç/g' |
sed 's/\\u00C8/È/g' |
sed 's/\\u00C9/É/g' |
sed 's/\\u00CA/Ê/g' |
sed 's/\\u00CB/Ë/g' |
sed 's/\\u00CC/Ì/g' |
sed 's/\\u00CD/Í/g' |
sed 's/\\u00CE/Î/g' |
sed 's/\\u00CF/Ï/g' |
sed 's/\\u00D0/Ð/g' |
sed 's/\\u00D1/Ñ/g' |
sed 's/\\u00D2/Ò/g' |
sed 's/\\u00D3/Ó/g' |
sed 's/\\u00D4/Ô/g' |
sed 's/\\u00D5/Õ/g' |
sed 's/\\u00D6/Ö/g' |
sed 's/\\u00D7/×/g' |
sed 's/\\u00D8/Ø/g' |
sed 's/\\u00D9/Ù/g' |
sed 's/\\u00DA/Ú/g' |
sed 's/\\u00DB/Û/g' |
sed 's/\\u00DC/Ü/g' |
sed 's/\\u00DD/Ý/g' |
sed 's/\\u00DE/Þ/g' |
sed 's/\\u00DF/ß/g' |
sed 's/\\u00E0/à/g' |
sed 's/\\u00E1/á/g' |
sed 's/\\u00E2/â/g' |
sed 's/\\u00E3/ã/g' |
sed 's/\\u00E4/ä/g' |
sed 's/\\u00E5/å/g' |
sed 's/\\u00E6/æ/g' |
sed 's/\\u00E7/ç/g' |
sed 's/\\u00E8/è/g' |
sed 's/\\u00E9/é/g' |
sed 's/\\u00EA/ê/g' |
sed 's/\\u00EB/ë/g' |
sed 's/\\u00EC/ì/g' |
sed 's/\\u00ED/í/g' |
sed 's/\\u00EE/î/g' |
sed 's/\\u00EF/ï/g' |
sed 's/\\u00F0/ð/g' |
sed 's/\\u00F1/ñ/g' |
sed 's/\\u00F2/ò/g' |
sed 's/\\u00F3/ó/g' |
sed 's/\\u00F4/ô/g' |
sed 's/\\u00F5/õ/g' |
sed 's/\\u00F6/ö/g' |
sed 's/\\u00F7/÷/g' |
sed 's/\\u00F8/ø/g' |
sed 's/\\u00F9/ù/g' |
sed 's/\\u00FA/ú/g' |
sed 's/\\u00FB/û/g' |
sed 's/\\u00FC/ü/g' |
sed 's/\\u00FD/ý/g' |
sed 's/\\u00FE/þ/g' |
sed 's/\\u00FF/ÿ/g' |
sed 's/\\u00E4/ä/g' |
sed 's/\\u00F6/ö/g' |
sed 's/\\u00FC/ü/g' |
sed 's/\\u00DF/ß/g' |
sed 's/\\u00C4/Ä/g' |
sed 's/\\u00D6/Ö/g' |
sed 's/\\u00DC/Ü/g' |
sed 's/\\u201E/„/g' |
sed 's/\\u201C/“/g' |
sed 's/\\u2026/…/g' | 
sed 's/\\u2022/•/g' |
sed 's/\\u2153/⅓/g' |
sed 's/\\u2082/₂/g' |
sed "s/%22/'/g" |
sed "s/&#91;/[/g" |
sed "s/&#93;/]/g" |
sed "s/&#x5B;/[/g" | sed "s/&#x5D;/]/g" |
sed 's/> ./>      ./' |
sed "s/> </>	</g"| sed 's/> "/>	"/'|
sed "s/\\u2013/-/g" |
sed "s/\\u2019/’/g" > "$1.s"
mv "$1.s" "$1"

# != ...
 # – != -
 #  	’ != '