/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NetbaseJNI */

#ifndef _Included_NetbaseJNI
#define _Included_NetbaseJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NetbaseJNI
 * Method:    query
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NetbaseJNI_query
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
